### ISSUE TITLE
 rocksdb/utilities/debug.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by dreamquster** [pingcap/rust-rocksdb#104]
When compiling the tikv code, it report such error about librocksdb_sys-a40eeeb2edcbb581

**Comment by BusyJay** [comment]
We have upgraded rocksdb to 5.5.1+ recently, please make sure rocksdb in your system is up to date.

**Comment by dreamquster** [comment]
doc:https://github.com/pingcap/docs/blob/master/dev-guide/development.md
sh:https://github.com/pingcap/docs/blob/master/scripts/build_rocksdb.sh
still 5.4.6.

**Comment by BusyJay** [comment]
Sorry for the misleading information.

@siddontang we may need to enable static link by default and remove all rocksdb related messages from doc. So that we don't need to take care of different rocksdb version especially we update the library quite often.

**Comment by siddontang** [comment]
@BusyJay  +1
