### ISSUE TITLE
How to build it on windows?

### ISSUE THREAD

**Issue by dtcv** [pingcap/rust-rocksdb#156]
I use cargo build,but it returns:
failed to run custom build command for `librocksdb_sys v0.1.0 (file:///E:/rustproject/rust-rocksdb-master/librocksdb_sys)`.
so i want to know how to build rust-rocksdb on windows

**Comment by BusyJay** [comment]
Windwos support is quiet limited right now. You need to build a rocksdb native library, and then put it in a directory pointed by environment variables `LIB` and `LIBPATH`. Also `INCLUDE` is needed to be set properly.

After cmake is introduced, it maybe possible to build rust-rocksdb without building a rocksdb library. It maybe done in the near future, however there is no clear plan yet.

**Comment by dtcv** [comment]
Thanks for your guidance, i will try it.
