### ISSUE TITLE
Expose multi_get APIs

### ISSUE THREAD

**Issue by messense** [pingcap/rust-rocksdb#162]
Can we add high level APIs for [`crocksdb_multi_get`](https://github.com/pingcap/rust-rocksdb/blob/f6788b6452ab176fab78e031992a7e39c7a35420/librocksdb_sys/crocksdb/c.cc#L848) and [`crocksdb_multi_get_cf`](https://github.com/pingcap/rust-rocksdb/blob/f6788b6452ab176fab78e031992a7e39c7a35420/librocksdb_sys/crocksdb/c.cc#L878)?

**Comment by siddontang** [comment]
hi @messense 

There was a PR https://github.com/pingcap/rust-rocksdb/pull/59 to support this, but we found that we don't need this so close it. You can help us add this again.
