### ISSUE TITLE
Merge Operator while opening the DB in read only

### ISSUE THREAD

**Issue by Kerollmops** [pingcap/rust-rocksdb#213]
I am currently trying to use a RocksDB with read only settings (`DB::open_cf_for_read_only`) but I am not able to get keys from it, the DB crash with the following message:

```
Invalid argument: merge_operator is not properly initialized.
```

Note that I have previously created the DB (`DB::open`) and created two column families in it (`document` and `field`) and I have setup a merge operator on one of the two column family (`document`) using:

```rust
let mut options = ColumnFamilyOptions::new();
options.add_merge_operator("concat_operator", concat_operator); // defined elsewhere

db.create_cf(ColumnFamilyDescriptor{ name: "document", options })?;
db.create_cf("field")?;
```

Once I have filled the DB my program quit and another one read it in read only, as I say above.
But I don't know how to setup a merge operator on a specific column family when I am not creating it.

```rust
let mut opts = DBOptions::default();
opts.create_if_missing(false);

let cfds = vec!["document", "field"];

let dbpath = dbpath.as_ref().to_str().unwrap();
let mut db = DB::open_cf_for_read_only(opts, dbpath, cfds, false)?;

{
    // This code block doesn't seems to do anything at all
    // the error is already here even with that

    let doc_handle = db.cf_handle("document").expect("'document' cf not found");
    let mut cf_opt = db.get_options_cf(&doc_handle);
    cf_opt.add_merge_operator("concat_operator", concat_operator);
}

// use `db` here...
```

Is the method just missing in this wrapper ? Do I miss something ?

Thank you for your help.

**Comment by siddontang** [comment]
PTAL @huachaohuang

**Comment by Kerollmops** [comment]
Thank you I will try that out ! 👍
