### ISSUE TITLE
Merge result incorrect after database reopen

### ISSUE THREAD

**Issue by rgrochowicz** [pingcap/rust-rocksdb#223]
After a database is closed and reopened, the merges fail in some way.
Here's a sample repo: https://github.com/rgrochowicz/rust-rocksdb-merge-oddity

Notice that the read happens correctly if the key is read immediately after the merges, but fail after a reopen and the additional merges.

I'm expecting (50+50):
```
After first create: Ok(50) should be Ok(50)
After second create: Ok(100) should be Ok(100)
```

But receive (50+5?):
```
After first create: Ok(50) should be Ok(50)
After second create: Ok(55) should be Ok(100)
```

**Comment by evenyag** [comment]
I encountered a similar issue. My merged result seems odd after db reopened. I found out this line always set `new_value_length` to 1, which may cause this problem.

[https://github.com/pingcap/rust-rocksdb/blob/348b5bc94d1b7aee486f04c7aacca7f1712cdae0/src/merge_operator.rs#L91](https://github.com/pingcap/rust-rocksdb/blob/348b5bc94d1b7aee486f04c7aacca7f1712cdae0/src/merge_operator.rs#L91)

I am trying to fix that and maybe this [PR](https://github.com/pingcap/rust-rocksdb/pull/224) can also fix your problem.

**Comment by rgrochowicz** [comment]
Thanks @evenyag! I can confirm #224 fixes this issue.
