### ISSUE TITLE
rocksdb::DBWithTTL::Open support ?

### ISSUE THREAD

**Issue by fredchenbj** [pingcap/rust-rocksdb#225]
Would rocksdb::DBWithTTL::Open be supported ? We want to use this interface.

**Comment by siddontang** [comment]
I guess it may be easy to add, it is very appreciated that you can send us a PR. @fredchenbj

**Comment by fredchenbj** [comment]
@siddontang OK, I has finished the code, and will sent a PR recently.

**Comment by DorianZheng** [comment]
#227
