### ISSUE TITLE
Test inference warning

### ISSUE THREAD

**Issue by messense** [pingcap/rust-rocksdb#231]
warning: An explicit [[test]] section is specified in Cargo.toml which currently
disables Cargo from automatically inferring other test targets.
This inference behavior will change in the Rust 2018 edition and the following
files will be included as a test target:

* /home/travis/build/pingcap/rust-rocksdb/tests/test_rate_limiter.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_delete_files_in_range.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_delete_range.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_compact_range.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_prefix_extractor.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_ingest_external_file.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_event_listener.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_slice_transform.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_ttl.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_iterator.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_column_family.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_rocksdb_options.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_multithreaded.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_read_only.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_statistics.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_table_properties.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_metadata.rs
* /home/travis/build/pingcap/rust-rocksdb/tests/test_compaction_filter.rs

This is likely to break cargo build or cargo test as these files may not be
ready to be compiled as a test target today. You can future-proof yourself
and disable this warning by adding `autotests = false` to your [package]
section. You may also move the files to a location where Cargo would not
automatically infer them to be a target, such as in subfolders.
For more information on this warning you can consult
https://github.com/rust-lang/cargo/issues/5330

**Comment by huachaohuang** [comment]
Fixed in https://github.com/pingcap/rust-rocksdb/pull/243
