### ISSUE TITLE
reduce the redundant data copy for Get 

### ISSUE THREAD

**Issue by siddontang** [pingcap/rust-rocksdb#24]
The rocksdb_get API will first save data into a C++ string, then copy the string to a malloc buffer and return for outer use. 

Maybe we can reduce the redundant copy. We may return a C structure which wraps the c++ string directly. 

This may improve a little performance, but I still doubt whether it is worth to do or not.

**Comment by arthurprs** [comment]
The new get() api in rocksdb 5.4 should make this possible without hassle.

**Comment by siddontang** [comment]
@arthurprs 

It is cool, can you give us any discussion or reference about this?

**Comment by arthurprs** [comment]
I think this is the PR https://github.com/facebook/rocksdb/pull/1756

**Comment by andelf** [comment]
#62 fixes
