### ISSUE TITLE
Auto-tuned Rate Limiter 

### ISSUE THREAD

**Issue by gripleaf** [pingcap/rust-rocksdb#255]
whether the rust-rocksdb support auto tuned rate limiter which was mentioned in this [paper](https://www.percona.com/live/18/sites/default/files/RocksEFile-combined_032718.pdf) last year?

it item seems has an obviously impact on read/write latencies.

**Comment by siddontang** [comment]
PTAL @huachaohuang

**Comment by huachaohuang** [comment]
RocksDB supports that, we just need to add a wrapper for it, are you interested in adding one?

**Comment by gripleaf** [comment]
Of course!
I will submit a PR ASAP.

**Comment by DorianZheng** [comment]
#257
