### ISSUE TITLE
perf context test failure

### ISSUE THREAD

**Issue by fredchenbj** [pingcap/rust-rocksdb#318]
run `cargo test` on mac os, two asserts in src/perf_context.rs failed:
`assert_eq!(ctx.seek_internal_seek_time(), 0); `  L431
`assert_eq!(get_perf_level(), PerfLevel::EnableCount);`  L437

**Comment by yiwu-arbug** [comment]
@fredchenbj thanks for reporting. will check when we got a chance.

**Comment by yiwu-arbug** [comment]
@fredchenbj I'm not able to reproduce on my side. Which test fail on your side? What's your c++ compiler version? Thanks.

**Comment by fredchenbj** [comment]
@yiwu-arbug Sorry, I didn't describe it clearly. I use `cargo test -- --test-threads=1` failed at `perf_context::test::test_perf_context`, but `cargo test` works well.
