### ISSUE TITLE
LZ4 compiled without optimizations

### ISSUE THREAD

**Issue by arthurprs** [pingcap/rust-rocksdb#39]
Hi, I'm not sure (don't know much about make) but I noticed a few LZ4 functions on `perf top` and went to check.

I think setting CFLAGS here https://github.com/pingcap/rust-rocksdb/blob/master/librocksdb_sys/build.sh#L99 is preventing make to set optimizations flags downstream https://github.com/lz4/lz4/blob/dev/lib/Makefile#L48

I may be better to use MOREFLAGS for the `-fPIC`

**Comment by siddontang** [comment]
seem that we should add `-O3` here /cc @BusyJay
