### ISSUE TITLE
Should we make method signatures of IngestExternalFileOptions be consistent with others?

### ISSUE THREAD

**Issue by choleraehyq** [pingcap/rust-rocksdb#97]
All methods *move* the ownership and return it back to user. Like this:
`pub fn snapshot_consistent(self, whether_consistent: bool) -> IngestExternalFileOptions`
But other options methods just get a mutable reference and return nothing. Like this:
`pub fn set_memtable_prefix_bloom_size_ratio(&mut self, ratio: f64) {`

It's quite weird. Should we make them consistent?

@zhangjinpeng1987

**Comment by siddontang** [comment]
I prefer `move`,  but this may change the code a lot. 

/cc @BusyJay

**Comment by BusyJay** [comment]
Unless we use a builder to build an option, otherwise I prefer returning nothing or just returning a mutable reference.

**Comment by choleraehyq** [comment]
Fixed by https://github.com/pingcap/rust-rocksdb/pull/98.
